### ISSUE TITLE
Additional libs

### ISSUE THREAD

**Issue by avttrue** [alexeylysenko/CryptFileDevice#5]
Не могли бы вы указать, какие дополнительные библиотеки должны быть установлены для сборки данного кода?
Как я понял, это должно быть libssl и libcrypto++, как минимум, в случае Убунты:
sudo apt-get install libssl-dev
sudo apt-get install libcrypto++-dev

Кажется, всё. В любом случае, было бы правильно упомянуть это к пояснению по проекту.
И ещё вопрос. У конечного пользователя так же должны будут быть установлены данные библиотеки или можно собрать исполняемый файл "всё-в-одном"? :)
Спасибо!

**Comment by alexeylysenko** [comment]
Hi avttrue,

Thank you for the feedback. I prepared docker ubuntu image to be ready to build & run CryptFileDeviceExample without any additional actions. You can also check which libraries are needed to be installed on the "fresh" ubuntu distributive. I hope it helps to figure out what you need to use CryptFileDevice in your projects.
Regarding the second question it depends on how you link openssl library to your application. For static linkage you don't need anything installed on target machine (everything will be linked together with your application), for dynamic linkage you need to make sure there exist all dependencies on the target machine. But also keep in mind if you need just to run application you don't need all development dependencies (no need to install libssl-dev, instead you can install only libssl1.1 for example).
